### ISSUE TITLE
Create a new design for the portfolio

### ISSUE THREAD

**Issue by AnkitSharmaOnGithub** [AnkitSharmaOnGithub/Portfolio#1]
You need to suggest and create a newer design for the portfolio.

**Comment by yash0501** [comment]
Can I help you with this issue?

**Comment by SahrulRozak** [comment]
maybe I will make a little different ...

**Comment by agaveyonatan** [comment]
Hey, i can change your portfolio much better with css framework. Here is my project with css framework: https://coronatimes.vercel.app/

**Comment by AnkitSharmaOnGithub** [comment]
> Can I help you with this issue?

> Hi, can you assign me to this? Thanks :)

Hello. This issue has been fixed. Kindly visit :- https://github.com/AnkitSharmaOnGithub/covid19 for new issues and feel free to work on them,

**Comment by AnkitSharmaOnGithub** [comment]
> maybe I will make a little different ...

Hello. This issue has been fixed. Kindly visit :- https://github.com/AnkitSharmaOnGithub/covid19 for new issues and feel free to work on them,

**Comment by AnkitSharmaOnGithub** [comment]
> Hey, i can change your portfolio much better with css framework. Here is my project with css framework: https://coronatimes.vercel.app/

Hello. This issue has been fixed. Kindly visit :- https://github.com/AnkitSharmaOnGithub/covid19 for new issues and feel free to work on them,
