### ISSUE TITLE
Change the mobile view of the portfolio more attractive.

### ISSUE THREAD

**Issue by AnkitSharmaOnGithub** [AnkitSharmaOnGithub/Portfolio#2]
Mobile view of the portfolio more attractive uses a background image on alternate sections. Kindly change it with other background textures that looks good.

**Comment by Dheeraj-01** [comment]
Hi, can you assign me to this? Thanks :)

**Comment by AnkitSharmaOnGithub** [comment]
> Hi, can you assign me to this? Thanks :)

Hello

**Comment by Dheeraj-01** [comment]
can I work on that??

**Comment by AnkitSharmaOnGithub** [comment]
> Hi, can you assign me to this? Thanks :)

Hello Dheeraj. This issue has been fixed. Kindly visit :- https://github.com/AnkitSharmaOnGithub/covid19 for new issues.

**Comment by Dheeraj-01** [comment]
ok thanks😊
